version: '3.8'
services:
  web:
    build: .
    ports: ['3005:3000']
    env_file:
        - .env
    environment:
      NEXT_PUBLIC_API_HOST: ${NEXT_PUBLIC_API_HOST}
    networks:
      - thesis-network


networks:
  thesis-network:
    external: true
    name: thesis-network